rules:
  - name: pixiv(ranking)
    fileName: v1_pixiv_ranking.yaml
    favicon: favicon_pixiv.ico
    canSearch: true

  - name: pixiv(discovery)
    fileName: v1_pixiv_discovery.yaml
    favicon: favicon_pixiv.ico
    canSearch: true

  - name: yande
    fileName: v1_yande.yaml
    favicon: favicon_yande.ico
    canSearch: true

  - name: konachan
    fileName: v1_konachan.yaml
    favicon: favicon_konachan.ico
    canSearch: true

  - name: zerochan
    fileName: v1_zerochan.yaml
    favicon: favicon_zerochan.ico
    canSearch: true

  - name: shuushuu
    fileName: v1_shuushuu.yaml
    favicon: favicon_shuushuu.ico
    canSearch: true

  - name: danbooru
    fileName: v1_danbooru.yaml
    favicon: favicon_danbooru.png
    canSearch: true

  - name: safebooru
    fileName: v1_safebooru.yaml
    favicon: favicon_safebooru.ico
    canSearch: true

  - name: gelbooru
    fileName: v1_gelbooru.yaml
    favicon: favicon_gelbooru.png
    canSearch: true

  - name: anime_pictures
    fileName: v1_anime_pictures.yaml
    favicon: favicon_anime_pictures.png
    canSearch: true

  - name: minitokyo
    fileName: v1_minitokyo.yaml
    favicon: favicon_minitokyo.jpg
    canSearch: true

  - name: konchan_chs
    fileName: v1_konchan_chs.yaml
    favicon: favicon_konchan_chs.png
    canSearch: true

  - name: konachan(pool)
    fileName: v1_konachan_pool.yaml
    favicon: favicon_konachan_pool.ico
    canSearch: true

  - name: yande(pool)
    fileName: v1_yande_pool.yaml
    favicon: favicon_yande_pool.ico
    canSearch: true

  - name: danbooru(pool)
    fileName: v1_danbooru_pool.yaml
    favicon: favicon_danbooru_pool.png
    canSearch: false